- id: update_morning_commute_sensor
  alias: "Commute - Update morning commute sensor"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_destination_1
- id: create_weekly_backup
  alias: "Backup - Create snapshot weekly"
  initial_state: 'on'
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Hassio - {{now().strftime('%y-%m-%d')}}
    - service: hassio.addon_stdin
      data_template:
        addon: 7be23ff5_dropbox_sync
        input: {"command":"upload"}
- id: netatmo_ftp_clean_up
  alias: "Netatmo - FTP clean up"
  initial_state: 'on'
  trigger:
    platform: time_pattern
    hours: "*"
    minutes: "00"
  action:
    - service: shell_command.netatmo_ftp_clean_up
