- id: update_morning_commute_sensor
  alias: "Commute - Update morning commute sensor"
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:30:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_destination_1
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_destination_2
