- id: update_morning_commute_sensor
  alias: "Commute - Update morning commute sensor"
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_destination_1
- id: create_weekly_backup
  alias: "Backup - Create snapshot weekly"
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - fri
  action:
    - service: hassio.backup_partial
      data:
        name: Hassio - {{now().strftime('%y-%m-%d')}}
        addons:
          - core_ssh
          - core_git_pull
          - a0d7b954_ftp
        folders:
          - homeassistant
          - addons/local
          - ssl
- id: dropbox_sync_upload
  alias: "Dropbox sync - Backup"
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - fri
  action:
    - service: shell_command.dropbox_sync
- id: netatmo_ftp_clean_up
  alias: "Netatmo - FTP clean up"
  trigger:
    platform: time_pattern
    hours: "*"
    minutes: "00"
  action:
    - service: shell_command.netatmo_ftp_clean_up
- id: r7000_backup
  alias: "R7000 - Backup"
  trigger:
    platform: time
    at: '05:00:00'
  condition:
    condition: time
    weekday:
      - mon
  action:
    - service: shell_command.r7000_backup
      data:
        username: !secret r7000_username
        password: !secret r7000_password
        router_ip: !secret r7000_router_ip
- id: notify_internet_disconnection
  alias: "Notify - Internet disconnection"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.internet_connection
      from: 'on'
      to: 'off'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Internet connection lost"
        title: "Oh noes! 😖"
- id: notify_internet_connection
  alias: "Notify - Internet connection"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.internet_connection
      from: 'off'
      to: 'on'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Internet connection restored"
        title: "Yay! 🎉"
- id: notify_vigicrue
  alias: "Notify - Vigicrue"
  trigger:
    platform: numeric_state
    entity_id: sensor.rest_vigicrue_hydro_observation
    above: 1.8
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Vigicrue alert"
        title: "Above 1.8m 🌊"
- id: notify_suez_water
  alias: "Notify - Suez"
  trigger:
    platform: numeric_state
    entity_id: sensor.suez_water_client
    above: 500
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Suez alert"
        title: "Above 500L 💧"
- id: notify_dryer1_finished
  alias: "Notify - Dryer 1 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer1
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "00:45 finished"
- id: notify_dryer2_finished
  alias: "Notify - Dryer 2 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer2
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "01:20 finished"
- id: notify_dryer3_finished
  alias: "Notify - Dryer 3 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer3
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "03:00 finished"
