- id: update_morning_commute_sensor
  alias: "Commute - Update morning commute sensor"
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: time
      after: '07:00:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.google_travel_time_destination_1
- id: create_weekly_backup
  alias: "Backup - Create snapshot weekly"
  trigger:
    platform: time
    at: '04:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - fri
  action:
    - service: hassio.backup_partial
      data:
        name: Hassio - {{now().strftime('%y-%m-%d')}}
        addons:
          - core_ssh
          - core_git_pull
          - a0d7b954_ftp
          - core_mariadb
          - local-suez-tout-sur-mon-eau
          - local-edf-tempo
          - local-edf-electricity
        folders:
          - homeassistant
          - addons/local
          - ssl
- id: dropbox_sync_upload
  alias: "Dropbox sync - Backup"
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: time
    weekday:
      - mon
      - fri
  action:
    - service: shell_command.dropbox_sync
- id: netatmo_ftp_clean_up
  alias: "Netatmo - FTP clean up"
  trigger:
    platform: time_pattern
    hours: "*"
    minutes: "00"
  action:
    - service: shell_command.netatmo_ftp_clean_up
# - id: r7000_backup
#   alias: "R7000 - Backup"
#   trigger:
#     platform: time
#     at: '05:00:00'
#   condition:
#     condition: time
#     weekday:
#       - mon
#   action:
#     - service: shell_command.r7000_backup
#       data:
#         username: !secret r7000_username
#         password: !secret r7000_password
#         router_ip: !secret r7000_router_ip
- id: notify_fiber_disconnection
  alias: "Notify - Fiber disconnection"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.fiber_connection
      from: 'on'
      to: 'off'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Fiber connection lost"
        title: "Oh noes! 😖"
- id: notify_fiber_connection
  alias: "Notify - Fiber connection"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.fiber_connection
      from: 'off'
      to: 'on'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Fiber connection restored"
        title: "Yay! 🎉"
- id: notify_vigicrue
  alias: "Notify - Vigicrue"
  trigger:
    platform: numeric_state
    entity_id: sensor.rest_vigicrue_hydro_observation
    above: 2.0
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Vigicrue alert"
        title: "Above 1.8m 🌊"
- id: notify_suez_water
  alias: "Notify - Suez"
  trigger:
    platform: numeric_state
    entity_id: sensor.suez_water_consumption
    above: 500
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Suez alert"
        title: "Above 500L 💧"
- id: notify_dryer1_finished
  alias: "Notify - Dryer 1 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer1
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "00:45 finished"
- id: notify_dryer2_finished
  alias: "Notify - Dryer 2 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer2
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "01:05 finished"
- id: notify_dryer3_finished
  alias: "Notify - Dryer 3 finished"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.dryer3
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Dryer ♨️"
        title: "02:00 finished"
- id: aqara_dryer1_pressed
  alias: "Button - Dryer 1 pressed"
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 4a935d6fdf67c4b4ee185ebe93011d77
  condition:
    - condition: template
      value_template: '{{ trigger.event.data.command == "single" }}'
  action:
    - service: timer.start
      target:
        entity_id: timer.dryer1
- id: aqara_dryer2_pressed
  alias: "Button - Dryer 2 pressed"
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 4a935d6fdf67c4b4ee185ebe93011d77
  condition:
    - condition: template
      value_template: '{{ trigger.event.data.command == "double" }}'
  action:
    - service: timer.start
      target:
        entity_id: timer.dryer2
- id: aqara_dryer3_pressed
  alias: "Button - Dryer 3 pressed"
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 4a935d6fdf67c4b4ee185ebe93011d77
  condition:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
  action:
    - service: timer.start
      target:
        entity_id: timer.dryer3
- id: notify_edf_tempo
  alias: "Notify - EDF Tempo"
  trigger:
    - platform: state
      entity_id: sensor.tempo_tomorrow
      not_to:
        - NON_DEFINI
  action:
    - service: !secret notify_mobile_me
      data:
        message: "EDF Tempo - Tomorrow"
        title: "{{ states('sensor.tempo_tomorrow')|replace('TEMPO_', '')|capitalize }} ⚡"
# - id: toggle_light_bulb
#   alias: "Light - Toggle light bulb"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.mini_pir_sensor_motion
#   action:
#     - service: "light.turn_{{ trigger.to_state.state }}"
#       target:
#         entity_id: light.light_bulb_zigbee_light
- id: notify_letter_box_opened
  alias: "Notify - Letter box opened"
  trigger:
    - platform: state
      entity_id: binary_sensor.mini_pir_sensor_motion
      from: 'off'
      to: 'on'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Letter box opened"
        title: "✉️ opened"
- id: notify_letter_box_closed
  alias: "Notify - Letter box closed"
  trigger:
    - platform: state
      entity_id: binary_sensor.mini_pir_sensor_motion
      from: 'on'
      to: 'off'
  action:
    - service: !secret notify_mobile_me
      data:
        message: "Letter box closed"
        title: "✉️ closed"
- id: start_edf_tempo_addon
  alias: "EDF Tempo - Start addon"
  trigger:
    - platform: time_pattern
      minutes: '05'
  action:
    - service: hassio.addon_start
      data:
        addon: local_edf-tempo
- id: start_edf_electricity
  alias: "EDF Electricity - Start addon"
  trigger:
    - platform: time_pattern
      hours: "22"
      minutes: "10"
  action:
    - service: hassio.addon_start
      data:
        addon: local_edf-electricity
- id: start_suez_water
  alias: "Suez Water - Start addon"
  trigger:
    - platform: time_pattern
      hours: "22"
      minutes: "20"
  action:
    - service: hassio.addon_start
      data:
        addon: local_suez_tout_sur_mon_eau
