homeassistant:
  auth_providers:
    - type: homeassistant
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris

# Integration, users, etc.
config:

# Sunset and sunrise time
sun:

# Frontend config (see ./ui-lovelace.yaml)
frontend:
lovelace:
  mode: yaml
  resources:
    - url: /local/components/weather-card/weather-card.js
      type: module

# System health report
system_health:

# Philips Hue
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: false
      allow_unreachable: true

# Netatmo
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

# Tuya plugs
tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 33

# Google Chromecast
cast:
  media_player:
    - host: !secret cast_host

# Not working, need to update the component in ha/core (now using client/secret)
# Enedis Linky
# linky:
#   - username: !secret linky_username
#     password: !secret linky_password

sensor:
  # Google Travel Time
  # - platform: google_travel_time
  #   entity_namespace: google_travel_time_destination_1
  #   api_key: !secret google_travel_time_api_key
  #   name: !secret google_travel_time_name_1
  #   origin: !secret google_travel_time_origin_home
  #   destination: !secret google_travel_time_destination_1
  #   scan_interval: 15
  #   options:
  #     mode: driving
  #     departure_time: now
  #     avoid: tolls

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
