homeassistant:
  auth_providers:
    - type: homeassistant
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris
  country: FR

# Integration, users, history, etc.
config:
history:
  include:
    entities:
      - binary_sensor.internet_connection
      - sensor.suez_water_client
      - sensor.rest_vigicrue_hydro_observation
      - sensor.rasp_temperature

# Sunset and sunrise time
sun:

# Frontend config (see ./ui-lovelace.yaml)
frontend:
lovelace:
  mode: yaml

# System health report
system_health:

# Philips Hue
hue:
  bridges:
    - host: !secret hue_host
      allow_hue_groups: false
      allow_unreachable: true

# Netatmo
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

# Wait for implementation on RPi + sniffing codes (https://github.com/ninjablocks/433Utils)
# switch:
#   - platform: rpi_rf
#     gpio: 0 # todo
#     switches:
#       outlet_1:
#         code_on: 11111 # todo
#         code_off: 00000 # todo
#       outlet_2:
#         code_on: 11111 # todo
#         code_off: 00000 # todo

sensor:
  # Google Travel Time (trip durations)
  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    name: google_travel_time_destination_1
    origin: !secret google_travel_time_origin_home
    destination: !secret google_travel_time_destination_1
    scan_interval: 900
    options:
      mode: driving
      departure_time: now
      avoid: tolls
  # Vigicrue (flood monitoring)
  - platform: rest
    name: rest_vigicrue_hydro_observation
    resource: !secret rest_vigicrue_hydro_observation_url
    method: !secret rest_vigicrue_hydro_observation_method
    value_template: '{{value_json.Serie.ObssHydro[-1].ResObsHydro}}'
    json_attributes_path: Serie
    json_attributes:
      - CdStationHydro
      - LbStationHydro
    scan_interval: 300
    state_class: measurement
    unit_of_measurement: m
    device_class: water

  # Transilien (trains)
  # - platform: rest
  #   name: rest_transilien_search
  #   resource: !secret rest_transilien_search_url
  #   method: !secret rest_transilien_search_method
  #   payload: !secret rest_transilien_search_payload
  #   headers:
  #     Content-Type: application/json
  #   value_template: '{{value_json.nextTrainsList[0].departureTime}}'
  #   json_attributes:
  #     - nextTrainsList
  #   scan_interval: 60
  # Suez (water consumption)
  - platform: suez_water
    username: !secret suez_water_consumption_username
    password: !secret suez_water_consumption_password
    counter_id: !secret suez_water_consumption_counter_id
    state_class: measurement
  # Raspberry Pi CPU temperature
  - platform: command_line
    name: rasp_temperature
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    value_template: '{{value | multiply(0.001) | round}}'
    scan_interval: 900
    state_class: measurement
    unit_of_measurement: °C
    device_class: temperature

binary_sensor:
  - platform: ping
    host: !secret home_ip_addr
    count: 2
    scan_interval: 10
    name: internet_connection

timer:
  laundry1:
    duration: '01:30:00'
  laundry2:
    duration: '02:00:00'
  dryer1:
    duration: '00:45:00'
  dryer2:
    duration: '01:10:00'
  dryer3:
    duration: '03:00:00'

# Shell commands
shell_command:
  netatmo_ftp_clean_up: bash /config/shell/netatmo_ftp_clean_up.sh
  r7000_backup: bash /config/shell/r7000_backup.sh {{ credentials }} {{ router_ip }}

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
