homeassistant:
  auth_providers:
    - type: homeassistant
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Paris
  country: FR

# Integration, users, history, etc.
config:
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 32
  include: !include history_include.yaml
history:
logbook:
  include: !include history_include.yaml
logger:
  default: warning
  logs:
    homeassistant.components.shell_command: debug

# Mobile app for notifications
mobile_app:

# Home Assistant "My Button" for integration redirections
my:

# Sunset and sunrise time
sun:

# Frontend config (see ./ui-lovelace.yaml)
frontend:
lovelace:
  mode: yaml

# System health report
system_health:

# Philips Hue
# hue:
#   bridges:
#     - host: !secret hue_host
#       allow_hue_groups: false
#       allow_unreachable: true

# Wait for implementation on RPi + sniffing codes (https://github.com/ninjablocks/433Utils)
# switch:
#   - platform: rpi_rf
#     gpio: 0 # todo
#     switches:
#       outlet_1:
#         code_on: 11111 # todo
#         code_off: 00000 # todo
#       outlet_2:
#         code_on: 11111 # todo
#         code_off: 00000 # todo

sensor:
  # Google Travel Time (trip durations)
  # - platform: google_travel_time
  #   api_key: !secret google_travel_time_api_key
  #   name: google_travel_time_destination_1
  #   origin: !secret google_travel_time_origin_home
  #   destination: !secret google_travel_time_destination_1
  #   scan_interval: 900
  #   options:
  #     mode: driving
  #     departure_time: now
  #     avoid: tolls

  # Vigicrue (flood monitoring)
  - platform: rest
    name: rest_vigicrue_hydro_observation
    resource: !secret rest_vigicrue_hydro_observation_url
    method: !secret rest_vigicrue_hydro_observation_method
    value_template: '{{value_json.Serie.ObssHydro[-1].ResObsHydro}}'
    json_attributes_path: Serie
    json_attributes:
      - CdStationHydro
      - LbStationHydro
    scan_interval: 900
    state_class: measurement
    unit_of_measurement: m
    device_class: distance

  # Transilien (trains)
  # - platform: rest
  #   name: rest_transilien_search
  #   resource: !secret rest_transilien_search_url
  #   method: !secret rest_transilien_search_method
  #   payload: !secret rest_transilien_search_payload
  #   headers:
  #     Content-Type: application/json
  #   value_template: '{{value_json.nextTrainsList[0].departureTime}}'
  #   json_attributes:
  #     - nextTrainsList
  #   scan_interval: 60

  # Internet Healthcheck
  - platform: rest
    resource: !secret healthcheck_internet_url
    name: healthcheck_internet
    method: GET
    timeout: 10
    scan_interval: 30
    value_template: '{{value}}'

binary_sensor:
  - platform: ping
    host: !secret home_ip_addr
    count: 2
    scan_interval: 10
    name: fiber_connection

command_line:
    # Raspberry Pi CPU temperature
  - sensor:
      name: rasp_temperature
      command: 'cat /sys/class/thermal/thermal_zone0/temp'
      value_template: '{{value | multiply(0.001) | round}}'
      scan_interval: 900
      unit_of_measurement: °C

timer:
  dryer1:
    duration: '00:45:00'
    icon: mdi:tumble-dryer
  dryer2:
    duration: '01:20:00'
    icon: mdi:tumble-dryer
  dryer3:
    duration: '03:00:00'
    icon: mdi:tumble-dryer

# Shell commands
shell_command:
  netatmo_ftp_clean_up: bash /config/shell/netatmo_ftp_clean_up.sh
  r7000_backup: bash /config/shell/r7000_backup.sh {{ username }} {{ password }} {{ router_ip }}
  dropbox_sync: bash /config/shell/dropbox_sync.sh / 10

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
