title: !secret home_name

views:
  - title: !secret home_name
    id: home_view
    cards:
      - type: history-graph
        title: 'Internet connectivity'
        hours_to_show: 72
        entities:
          - binary_sensor.internet_connection
      - type: statistics-graph
        title: 'Water consumption'
        chart_type: bar
        period: day
        days_to_show: 30
        stat_types:
          - state
          - mean
          - sum
        entities:
          - sensor.suez_water
