title: !secret home_name
views:
  - icon: mdi:home-assistant
    id: home
    title: !secret home_name
    cards:
      - type: weather-forecast
        name: Weather
        entity: weather.mimi_home
