title: !secret home_name

views:
  - title: !secret home_name
    id: home_view
    cards:
      - type: history-graph
        title: 'Internet connectivity'
        hours_to_show: 720
        entities:
          - binary_sensor.internet_connection
      - type: history-graph
        title: 'Water consumption'
        hours_to_show: 720
        entities:
          - sensor.suez_water_client
      - type: history-graph
        title: 'Vigicrue'
        hours_to_show: 720
        entities:
          - sensor.rest_vigicrue_hydro_observation
      - type: history-graph
        title: 'Raspberry Pi temperature'
        hours_to_show: 720
        entities:
          - sensor.rasp_temperature
