title: !secret home_name

resources:
  - url: "https://cdn.jsdelivr.net/npm/chart.js@4.5.0"
    type: js
  - url: "https://cdn.jsdelivr.net/npm/date-fns@4.1.0"
    type: js
  - url: "https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0"
    type: js
  - url: /local/chart-card.js
    type: module

views:
  - title: !secret home_name
    id: home_view
    cards:
      # Fiber connectivity
      - type: logbook
        title: 'Fiber connectivity'
        entities:
          - binary_sensor.fiber_connection
        hours_to_show: 504 # 3 weeks

      # Dryer
      - type: entities
        entities:
          - entity: timer.dryer1
            name: Dryer 00:45
          - entity: timer.dryer2
            name: Dryer 01:05
          - entity: timer.dryer3
            name: Dryer 02:00

      # EDF Tempo
      - type: entities
        entities:
          - entity: sensor.tempo_today
            name: Today
            icon: mdi:home-lightning-bolt
          - entity: sensor.tempo_tomorrow
            name: Tomorrow
            icon: mdi:home-lightning-bolt-outline
          - entity: sensor.remaining_bleu_days
            name: Bleu remaining
            icon: mdi:calendar-multiselect
          - entity: sensor.remaining_blanc_days
            name: Blanc remaining
            icon: mdi:calendar-multiselect
          - entity: sensor.remaining_rouge_days
            name: Rouge remaining
            icon: mdi:calendar-multiselect

      # Battery levels
      - type: entities
        entities:
          - entity: sensor.netatmo_anemometer_battery_percent
            name: Anemometer
          - entity: sensor.netatmo_attic_battery_percent
            name: Attic
          - entity: sensor.netatmo_backyard_battery_percent
            name: Backyard
          - entity: sensor.netatmo_bedroom1_battery_percent
            name: Bedroom (N)
          - entity: sensor.netatmo_master_bedroom_battery_percent
            name: Bedroom (C)
          - entity: sensor.netatmo_rain_gauge_battery_percent
            name: Rain gauge
          - entity: sensor.thermostat_battery_percent_2
            name: Thermostat
          - entity: sensor.aqara_mini_switch_battery
            name: Aqara mini switch

      # Stats
      # Suez water
      - type: "custom:chart-card"
        title: 'Suez water'
        entity: sensor.suez_water_consumption

      - type: history-graph
        title: 'Energy'
        hours_to_show: 720
        entities:
          - entity: sensor.tempo_today
            name: 'Tempo color'
          - entity: sensor.edf_electricity_consumption_kwh
            name: 'Electricity consumption'
          - entity: sensor.edf_gas_consumption_kwh
            name: 'Gas consumption'
          - entity: sensor.edf_electricity_consumption_cost
            name: 'Electricity cost'
          - entity: sensor.edf_gas_consumption_cost
            name: 'Gas cost'

      - type: history-graph
        title: 'Temperature'
        hours_to_show: 48
        entities:
          - entity: sensor.netatmo_attic_temperature
            name: 'Attic'
          - entity: sensor.netatmo_bedroom1_temperature
            name: 'Child 1 bedroom'
          - entity: sensor.netatmo_master_bedroom_temperature
            name: 'Child 2 bedroom'
          - entity: sensor.netatmo_living_room_temperature
            name: 'Living room'
          - entity: sensor.netatmo_mimi_health_coach_temperature
            name: 'Master bedroom'
          - entity: sensor.netatmo_backyard_temperature
            name: 'Backyard'

      - type: history-graph
        title: 'Humidity'
        hours_to_show: 48
        entities:
          - entity: sensor.netatmo_attic_humidity
            name: 'Attic'
          - entity: sensor.netatmo_bedroom1_humidity
            name: 'Child 1 bedroom'
          - entity: sensor.netatmo_master_bedroom_humidity
            name: 'Child 2 bedroom'
          - entity: sensor.netatmo_living_room_humidity
            name: 'Living room'
          - entity: sensor.netatmo_mimi_health_coach_humidity
            name: 'Master bedroom'
          - entity: sensor.netatmo_backyard_humidity
            name: 'Backyard'

      - type: history-graph
        title: 'CO2'
        hours_to_show: 48
        entities:
          - entity: sensor.netatmo_attic_co2
            name: 'Attic'
          - entity: sensor.netatmo_bedroom1_co2
            name: 'Child 1 bedroom'
          - entity: sensor.netatmo_master_bedroom_co2
            name: 'Child 2 bedroom'
          - entity: sensor.netatmo_living_room_co2
            name: 'Living room'
          - entity: sensor.netatmo_mimi_health_coach_co2
            name: 'Master bedroom'

      - type: history-graph
        title: 'Battery'
        hours_to_show: 720
        entities:
          - entity: sensor.netatmo_attic_battery_percent
            name: 'Attic'
          - entity: sensor.netatmo_bedroom1_battery_percent
            name: 'Child 1 bedroom'
          - entity: sensor.netatmo_master_bedroom_battery_percent
            name: 'Child 2 bedroom'
          - entity: sensor.netatmo_anemometer_battery_percent
            name: 'Anemometer'
          - entity: sensor.netatmo_backyard_battery_percent
            name: 'Backyard'
          - entity: sensor.netatmo_rain_gauge_battery_percent
            name: 'Rain gauge'
          - entity: sensor.thermostat_battery_percent_2
            name: 'Themostat'

      - type: history-graph
        title: 'Rain and river level'
        hours_to_show: 72
        entities:
          - entity: sensor.rest_vigicrue_hydro_observation
            name: 'River level'
          - entity: sensor.netatmo_rain_gauge_rain
            name: 'Rain gauge'

      # Cameras
      - type: picture-entity
        entity: camera.mimi_camera
      - type: picture-entity
        entity: camera.mimi_outdoor_camera
      - type: picture-entity
        entity: camera.sonnette

      # Letter box
      - type: logbook
        title: 'Letter box'
        entities:
          - binary_sensor.mini_pir_sensor_motion
        hours_to_show: 504 # 3 weeks
