title: !secret home_name

views:
  - title: !secret home_name
    id: home_view
    cards:
      # Fiber connectivity
      - type: logbook
        title: 'Fiber connectivity'
        entities:
          - binary_sensor.fiber_connection
        hours_to_show: 744 # 31 days

      # Dryer
      - type: entities
        entities:
          - entity: timer.dryer1
            name: Dryer 00:45
          - entity: timer.dryer2
            name: Dryer 01:20
          - entity: timer.dryer3
            name: Dryer 03:00

      # Battery levels
      - type: entities
        entities:
          - entity: sensor.netatmo_anemometer_battery_percent
            name: Anemometer
          - entity: sensor.netatmo_attic_battery_percent
            name: Attic
          - entity: sensor.netatmo_backyard_battery_percent
            name: Backyard
          - entity: sensor.netatmo_bedroom1_battery_percent
            name: Bedroom (N)
          - entity: sensor.netatmo_master_bedroom_battery_percent
            name: Bedroom (C)
          - entity: sensor.netatmo_rain_gauge_battery_percent
            name: Rain gauge
          - entity: sensor.thermostat_battery_percent_2
            name: Thermostat

      # Stats
      - type: history-graph
        hours_to_show: 720
        title: 'Water'
        entities:
          - entity: sensor.suez_water_consumption
            name: 'Consumption'

      - type: statistics-graph
        title: 'Water'
        chart_type: bar
        entities:
          - entity: sensor.suez_water_consumption
            name: Consumption

      - type: statistics-graph
        title: 'Power'
        chart_type: line
        entities:
          - entity: sensor.edf_electricity_consumption_kwh
            name: Consumption
          - entity: sensor.edf_electricity_consumption_cost
            name: Cost

      # Cameras
      - type: picture-entity
        entity: camera.mimi_camera
      - type: picture-entity
        entity: camera.mimi_outdoor_camera
