title: !secret home_name

views:
  - title: !secret home_name
    id: home_view
    cards:
      - type: logbook
        title: 'Internet connectivity'
        entities:
          - binary_sensor.internet_connection
        hours_to_show: 168
      - type: entities
        entities:
          - entity: timer.laundry1
            name: Laundry 01:30
          - entity: timer.laundry2
            name: Laundry 02:00
          - entity: timer.dryer1
            name: Dryer 00:45
          - entity: timer.dryer2
            name: Dryer 01:20
          - entity: timer.dryer3
            name: Dryer 03:00
